import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { REQUIREMENT_COVERAGE_GROUPS } from '../src/release/requirement-catalog'
import { ALL_DOMAIN_EVENT_TYPES, DOMAIN_EVENT_CATALOG } from '../src/shared/outbox'
import { ALL_QUEUE_NAMES } from '../src/shared/queue'
import { ALL_SCHEDULED_JOB_NAMES, SCHEDULED_JOB_CATALOG } from '../src/workers/scheduled-jobs'

const root = join(import.meta.dir, '..')
const workspace = join(root, '..')
const promptPath = join(workspace, 'innovation_backend_master_prompt.md')
const generatedDirectory = join(root, 'docs', 'generated')
const matrixPath = join(generatedDirectory, 'requirement-matrix.md')
const reportPath = join(root, 'docs', 'IMPLEMENTATION_REPORT.md')
const checkOnly = process.argv.includes('--check')

interface PromptSection {
  readonly number: number
  readonly title: string
}

function filesUnder(directory: string, predicate: (path: string) => boolean): string[] {
  const found: string[] = []
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) found.push(...filesUnder(path, predicate))
    else if (predicate(path)) found.push(path)
  }
  return found.sort()
}

function parsePromptSections(prompt: string): PromptSection[] {
  return [...prompt.matchAll(/^#{1,2} (\d+)\. (.+)$/gm)].map((match) => ({
    number: Number(match[1]),
    title: match[2]?.trim() ?? '',
  }))
}

function markdownPath(path: string): string {
  const absolute = join(root, path)
  const display = path.replace(/^\.\.\//, 'workspace/')
  const target = relative(generatedDirectory, absolute).replaceAll('\\', '/')
  return `[${display}](${target})`
}

function assertCatalogue(sections: readonly PromptSection[]): void {
  const known = new Set(sections.map((section) => section.number))
  const classified = new Map<number, string>()

  for (const group of REQUIREMENT_COVERAGE_GROUPS) {
    if (group.enforcement.length === 0 || group.provingTests.length === 0) {
      throw new Error(`Requirement group ${group.id} has no implementation or proving test.`)
    }
    for (const section of group.sections) {
      if (!known.has(section))
        throw new Error(`Requirement group ${group.id} names unknown §${section}.`)
      const duplicate = classified.get(section)
      if (duplicate !== undefined) {
        throw new Error(
          `Master prompt §${section} is classified by both ${duplicate} and ${group.id}.`,
        )
      }
      classified.set(section, group.id)
    }
    for (const path of [...group.enforcement, ...group.provingTests]) {
      if (!existsSync(join(root, path))) {
        throw new Error(`Requirement group ${group.id} cites missing evidence: ${path}`)
      }
    }
  }

  const missing = sections.filter((section) => !classified.has(section.number))
  if (missing.length > 0) {
    throw new Error(
      `Unclassified master-prompt sections: ${missing.map((item) => `§${item.number}`).join(', ')}`,
    )
  }
}

const prompt = readFileSync(promptPath, 'utf8')
const sections = parsePromptSections(prompt)
assertCatalogue(sections)

const migrations = readdirSync(join(root, 'prisma', 'migrations'), { withFileTypes: true }).filter(
  (entry) => entry.isDirectory(),
)
const tests = filesUnder(join(root, 'tests'), (path) => path.endsWith('.test.ts'))
const modules = readdirSync(join(root, 'src', 'modules'), { withFileTypes: true }).filter((entry) =>
  entry.isDirectory(),
)
const openapi = JSON.parse(readFileSync(join(root, 'docs', 'openapi.json'), 'utf8')) as {
  paths?: Record<string, Record<string, unknown>>
}
const openApiPaths = Object.keys(openapi.paths ?? {})
const openApiOperations = Object.values(openapi.paths ?? {}).reduce(
  (count, item) =>
    count +
    Object.keys(item).filter((method) =>
      ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'].includes(method),
    ).length,
  0,
)
const promptDigest = createHash('sha256').update(prompt).digest('hex')

const groupBySection = new Map(
  REQUIREMENT_COVERAGE_GROUPS.flatMap((group) =>
    group.sections.map((section) => [section, group] as const),
  ),
)

const matrixRows = sections.map((section) => {
  const group = groupBySection.get(section.number)
  if (group === undefined) throw new Error(`Missing classification for §${section.number}.`)
  return `| §${section.number} ${section.title} | ${group.status} | ${group.enforcement.map(markdownPath).join('<br>')} | ${group.provingTests.map(markdownPath).join('<br>')} | ${group.note} |`
})

const matrix = `<!-- GENERATED by scripts/generate-release-evidence.ts. Do not edit by hand. -->
# Master-prompt requirement matrix

This ledger classifies every numbered contract section in the master prompt. A
section is not considered evidenced unless its cited implementation and proving
test paths both exist. Endpoint-level and asynchronous catalogues have separate
executable parity tests; this document does not replace those gates.

- Master prompt SHA-256: \`${promptDigest}\`
- Classified numbered sections: ${sections.length}
- Coverage groups: ${REQUIREMENT_COVERAGE_GROUPS.length}
- Status vocabulary: \`implemented\`, \`conditional\`, \`not-applicable\`

| Requirement | Status | Enforcing component(s) | Proving test(s) | Audit note |
|---|---|---|---|---|
${matrixRows.join('\n')}
`

const eventRows = ALL_DOMAIN_EVENT_TYPES.map(
  (eventType) => `| \`${eventType}\` | \`${DOMAIN_EVENT_CATALOG[eventType]}\` |`,
).join('\n')
const schedulerRows = ALL_SCHEDULED_JOB_NAMES.map(
  (jobName) => `| \`${jobName}\` | \`${SCHEDULED_JOB_CATALOG[jobName].queue}\` |`,
).join('\n')

const report = `<!-- GENERATED by scripts/generate-release-evidence.ts. Do not edit by hand. -->
# Implementation evidence report

This report records repository evidence, not an unconditional production-ready
declaration. A release candidate is acceptable only when every current CI and
operator-controlled release gate succeeds in the target environment.

## Current evidence inventory

| Evidence | Count |
|---|---:|
| Numbered master-prompt sections classified | ${sections.length} |
| Application modules | ${modules.length} |
| Prisma migrations | ${migrations.length} |
| Test files | ${tests.length} |
| OpenAPI paths | ${openApiPaths.length} |
| OpenAPI operations | ${openApiOperations} |
| Domain event types | ${ALL_DOMAIN_EVENT_TYPES.length} |
| Registered queues | ${ALL_QUEUE_NAMES.length} |
| Recurring job schedulers | ${ALL_SCHEDULED_JOB_NAMES.length} |

The complete section mapping is generated in
[requirement-matrix.md](generated/requirement-matrix.md). Runtime/OpenAPI policy
parity is enforced by \`tests/security/route-policy-matrix.test.ts\`; event and
scheduler ownership are enforced by \`tests/queue/event-catalog.test.ts\` and
\`tests/queue/scheduled-jobs.test.ts\`.

## Domain event catalogue

| Event | Queue |
|---|---|
${eventRows}

## Recurring scheduler catalogue

| Job | Queue |
|---|---|
${schedulerRows}

## Release gate

Run \`bun run release:gate\` with the local PostgreSQL and Redis test services
available. CI additionally rebuilds from an empty database, checks migration
drift and generated artifacts, audits dependencies, produces an SBOM, scans the
container image, smoke-starts API/worker processes, and exercises graceful
shutdown. Provider health and backup/PITR restoration remain deployment-owner
acceptance gates because a source repository cannot prove external operations.
`

function emit(path: string, content: string): void {
  if (checkOnly) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      throw new Error(`${relative(root, path)} is stale. Run bun run evidence:generate.`)
    }
    return
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf8')
}

emit(matrixPath, matrix)
emit(reportPath, report)

if (!checkOnly) {
  console.log(`Generated ${relative(root, matrixPath)} and ${relative(root, reportPath)}.`)
} else {
  console.log('Generated requirement evidence is current and every numbered section is classified.')
}
