/**
 * Stable application error codes.
 *
 * These are part of the public API contract: clients branch on them. Codes are
 * never renamed or repurposed once shipped; a changed meaning gets a new code.
 * Messages are safe for end users and never contain SQL, stack traces, provider
 * payloads, secrets, or cross-tenant existence hints.
 */
export const ErrorCode = {
  // --- Generic -------------------------------------------------------------
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE: 'UNPROCESSABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',

  // --- Authentication / session -------------------------------------------
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  FRESH_SESSION_REQUIRED: 'FRESH_SESSION_REQUIRED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  CSRF_VALIDATION_FAILED: 'CSRF_VALIDATION_FAILED',

  // --- Authorization -------------------------------------------------------
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  ORGANIZATION_NOT_ACTIVE: 'ORGANIZATION_NOT_ACTIVE',
  MEMBERSHIP_REQUIRED: 'MEMBERSHIP_REQUIRED',
  NOT_ASSIGNED: 'NOT_ASSIGNED',

  // --- Idempotency ---------------------------------------------------------
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENT_REQUEST_IN_PROGRESS: 'IDEMPOTENT_REQUEST_IN_PROGRESS',

  // --- Organization lifecycle ---------------------------------------------
  ORGANIZATION_SLUG_TAKEN: 'ORGANIZATION_SLUG_TAKEN',
  APPLICATION_ALREADY_PENDING: 'APPLICATION_ALREADY_PENDING',
  APPLICATION_NOT_EDITABLE: 'APPLICATION_NOT_EDITABLE',
  APPLICATION_ALREADY_DECIDED: 'APPLICATION_ALREADY_DECIDED',
  LAST_OWNER_PROTECTED: 'LAST_OWNER_PROTECTED',
  ALREADY_A_MEMBER: 'ALREADY_A_MEMBER',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  ORGANIZATION_ARCHIVED: 'ORGANIZATION_ARCHIVED',

  // --- Invitations / join codes / join requests ---------------------------
  INVITATION_INVALID: 'INVITATION_INVALID',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_USED: 'INVITATION_ALREADY_USED',
  INVITATION_EMAIL_MISMATCH: 'INVITATION_EMAIL_MISMATCH',
  JOIN_CODE_INVALID: 'JOIN_CODE_INVALID',
  JOIN_CODE_EXPIRED: 'JOIN_CODE_EXPIRED',
  JOIN_CODE_EXHAUSTED: 'JOIN_CODE_EXHAUSTED',
  JOIN_CODE_DOMAIN_MISMATCH: 'JOIN_CODE_DOMAIN_MISMATCH',
  JOIN_REQUEST_ALREADY_PENDING: 'JOIN_REQUEST_ALREADY_PENDING',
  JOIN_POLICY_DISALLOWS: 'JOIN_POLICY_DISALLOWS',

  // --- Challenge lifecycle -------------------------------------------------
  CHALLENGE_SLUG_TAKEN: 'CHALLENGE_SLUG_TAKEN',
  CHALLENGE_NOT_PUBLISHED: 'CHALLENGE_NOT_PUBLISHED',
  CHALLENGE_ALREADY_PUBLISHED: 'CHALLENGE_ALREADY_PUBLISHED',
  CHALLENGE_STATE_INVALID: 'CHALLENGE_STATE_INVALID',
  CHALLENGE_CANCELLED: 'CHALLENGE_CANCELLED',
  SCHEDULE_INVALID: 'SCHEDULE_INVALID',
  DEADLINE_SHORTENING_BLOCKED: 'DEADLINE_SHORTENING_BLOCKED',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  SUBMISSION_WINDOW_CLOSED: 'SUBMISSION_WINDOW_CLOSED',
  TRACK_IN_USE: 'TRACK_IN_USE',

  // --- Terms / consent -----------------------------------------------------
  TERMS_ACCEPTANCE_REQUIRED: 'TERMS_ACCEPTANCE_REQUIRED',
  TERMS_VERSION_STALE: 'TERMS_VERSION_STALE',
  TERMS_VERSION_IMMUTABLE: 'TERMS_VERSION_IMMUTABLE',

  // --- Forms ---------------------------------------------------------------
  FORM_SCHEMA_INVALID: 'FORM_SCHEMA_INVALID',
  FORM_VERSION_IMMUTABLE: 'FORM_VERSION_IMMUTABLE',
  FORM_RESPONSE_INVALID: 'FORM_RESPONSE_INVALID',
  FORM_VERSION_NOT_PUBLISHED: 'FORM_VERSION_NOT_PUBLISHED',

  // --- Participation -------------------------------------------------------
  PARTICIPATION_POLICY_DISALLOWS: 'PARTICIPATION_POLICY_DISALLOWS',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  PARTICIPATION_NOT_FOUND: 'PARTICIPATION_NOT_FOUND',
  PARTICIPATION_STATE_INVALID: 'PARTICIPATION_STATE_INVALID',
  SCREENING_APPLICATION_REQUIRED: 'SCREENING_APPLICATION_REQUIRED',
  PARTICIPANT_DISQUALIFIED: 'PARTICIPANT_DISQUALIFIED',

  // --- Teams ---------------------------------------------------------------
  TEAM_FULL: 'TEAM_FULL',
  TEAM_TOO_SMALL: 'TEAM_TOO_SMALL',
  TEAM_NAME_TAKEN: 'TEAM_NAME_TAKEN',
  ALREADY_ON_A_TEAM: 'ALREADY_ON_A_TEAM',
  NOT_A_TEAM_MEMBER: 'NOT_A_TEAM_MEMBER',
  NOT_TEAM_CAPTAIN: 'NOT_TEAM_CAPTAIN',
  TEAM_LOCKED: 'TEAM_LOCKED',
  CAPTAIN_CANNOT_LEAVE: 'CAPTAIN_CANNOT_LEAVE',
  SOLO_PARTICIPATION_DISABLED: 'SOLO_PARTICIPATION_DISABLED',

  // --- Submissions ---------------------------------------------------------
  SUBMISSION_ALREADY_EXISTS: 'SUBMISSION_ALREADY_EXISTS',
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  SUBMISSION_ALREADY_FINALIZED: 'SUBMISSION_ALREADY_FINALIZED',
  SUBMISSION_REQUIREMENTS_UNMET: 'SUBMISSION_REQUIREMENTS_UNMET',
  SUBMISSION_VERSION_IMMUTABLE: 'SUBMISSION_VERSION_IMMUTABLE',
  SUBMISSION_DISQUALIFIED: 'SUBMISSION_DISQUALIFIED',
  SCREENSHOT_LIMIT_EXCEEDED: 'SCREENSHOT_LIMIT_EXCEEDED',
  INVALID_EXTERNAL_URL: 'INVALID_EXTERNAL_URL',

  // --- Judging -------------------------------------------------------------
  RUBRIC_VERSION_IMMUTABLE: 'RUBRIC_VERSION_IMMUTABLE',
  RUBRIC_NOT_ACTIVE: 'RUBRIC_NOT_ACTIVE',
  JUDGE_ASSIGNMENT_EXISTS: 'JUDGE_ASSIGNMENT_EXISTS',
  JUDGE_CONFLICT_DECLARED: 'JUDGE_CONFLICT_DECLARED',
  SCORECARD_LOCKED: 'SCORECARD_LOCKED',
  SCORECARD_INCOMPLETE: 'SCORECARD_INCOMPLETE',
  SCORE_OUT_OF_RANGE: 'SCORE_OUT_OF_RANGE',
  JUDGING_NOT_OPEN: 'JUDGING_NOT_OPEN',
  JUDGING_ALREADY_FINALIZED: 'JUDGING_ALREADY_FINALIZED',
  JUDGING_INCOMPLETE: 'JUDGING_INCOMPLETE',
  RESULTS_NOT_FINALIZED: 'RESULTS_NOT_FINALIZED',
  RESULTS_ALREADY_PUBLISHED: 'RESULTS_ALREADY_PUBLISHED',
  RESULTS_NOT_PUBLISHED: 'RESULTS_NOT_PUBLISHED',
  FEEDBACK_NOT_RELEASED: 'FEEDBACK_NOT_RELEASED',

  // --- Media / files -------------------------------------------------------
  MEDIA_PURPOSE_INVALID: 'MEDIA_PURPOSE_INVALID',
  MEDIA_ASSET_NOT_FOUND: 'MEDIA_ASSET_NOT_FOUND',
  MEDIA_ALREADY_CLAIMED: 'MEDIA_ALREADY_CLAIMED',
  MEDIA_VERIFICATION_FAILED: 'MEDIA_VERIFICATION_FAILED',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  FILE_SCAN_PENDING: 'FILE_SCAN_PENDING',
  FILE_QUARANTINED: 'FILE_QUARANTINED',

  // --- Integrations --------------------------------------------------------
  INTEGRATION_NOT_FOUND: 'INTEGRATION_NOT_FOUND',
  INTEGRATION_DELIVERY_FAILED: 'INTEGRATION_DELIVERY_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // --- Exports / analytics -------------------------------------------------
  EXPORT_TYPE_UNSUPPORTED: 'EXPORT_TYPE_UNSUPPORTED',
  EXPORT_NOT_READY: 'EXPORT_NOT_READY',
  EXPORT_EXPIRED: 'EXPORT_EXPIRED',
  EXPORT_CONCURRENCY_LIMIT: 'EXPORT_CONCURRENCY_LIMIT',

  // --- Support / moderation ------------------------------------------------
  TICKET_STATE_INVALID: 'TICKET_STATE_INVALID',
  REPORT_TARGET_INVALID: 'REPORT_TARGET_INVALID',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',

  // --- Innovation portfolio ------------------------------------------------
  INNOVATION_ALREADY_PROMOTED: 'INNOVATION_ALREADY_PROMOTED',
  INNOVATION_STAGE_TRANSITION_INVALID: 'INNOVATION_STAGE_TRANSITION_INVALID',
  INNOVATION_NOT_FOUND: 'INNOVATION_NOT_FOUND',
  METRIC_DEFINITION_INVALID: 'METRIC_DEFINITION_INVALID',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
