import { AuditAction, type AuditWriter } from '../../shared/audit'
import type { AccessContext } from '../../shared/authorization'
import { authorize, Permission } from '../../shared/authorization'
import type { AppConfig } from '../../shared/config/config.schema'
import type { PrismaTransactionClient, TenantTransactionRunner } from '../../shared/database'
import { conflict, ErrorCode, forbidden, notFound, validationFailed } from '../../shared/errors'
import type { Page, PaginationLimits } from '../../shared/http'
import { toPageRequest } from '../../shared/http'
import { newId } from '../../shared/ids'
import type { OutboxWriter } from '../../shared/outbox'
import { QueueName } from '../../shared/queue'
import { type RateLimiter, RateLimitPolicies } from '../../shared/rate-limit'
import type { ObjectStorage } from '../../shared/storage'
import type {
  DataExportRow,
  ExportFilters,
  ExportsRepository,
  ExportType,
} from './exports.repository'

/**
 * CSV data exports (master prompt section 24.1).
 *
 * A request creates the `DataExport` row and an outbox event in the same
 * transaction; the CSV itself is generated by the `export.requested` job
 * handler, asynchronously, using a deterministic storage key so a retried
 * job overwrites the same object rather than accumulating duplicates.
 */
export interface CreateExportInput {
  exportType: ExportType
  filters: ExportFilters
}

export interface ExportsService {
  prepareCreate(access: AccessContext, organizationId: string): Promise<void>
  create(
    access: AccessContext,
    organizationId: string,
    input: CreateExportInput,
    transaction?: PrismaTransactionClient,
  ): Promise<DataExportRow>
  list(
    access: AccessContext,
    organizationId: string,
    query: { limit?: number; cursor?: string },
  ): Promise<Page<DataExportRow>>
  get(access: AccessContext, organizationId: string, exportId: string): Promise<DataExportRow>
  getDownloadUrl(
    access: AccessContext,
    organizationId: string,
    exportId: string,
  ): Promise<{ downloadUrl: string; expiresAt: string }>
  remove(access: AccessContext, organizationId: string, exportId: string): Promise<void>
}

function validateFilters(exportType: ExportType, filters: ExportFilters): ExportFilters {
  if (exportType === 'CHALLENGE_RESULTS' && filters.challengeId === undefined) {
    throw validationFailed('CHALLENGE_RESULTS exports require a challengeId filter.', [
      { field: 'filters.challengeId', code: 'required', message: 'A challengeId is required.' },
    ])
  }
  if (exportType === 'ORGANIZATION_MEMBERS') {
    // Members are organization-wide by definition; a challenge filter here
    // would be a silently-ignored no-op, so reject it instead.
    if (filters.challengeId !== undefined) {
      throw validationFailed('ORGANIZATION_MEMBERS exports do not accept a challengeId filter.', [
        {
          field: 'filters.challengeId',
          code: 'not_allowed',
          message: 'Not applicable to this export type.',
        },
      ])
    }
    return {}
  }
  return filters.challengeId === undefined ? {} : { challengeId: filters.challengeId }
}

export function createExportsService(
  repository: ExportsRepository,
  transactions: TenantTransactionRunner,
  audit: AuditWriter,
  outbox: OutboxWriter,
  objectStorage: ObjectStorage,
  rateLimiter: RateLimiter,
  config: AppConfig,
  limits: PaginationLimits,
): ExportsService {
  return {
    async prepareCreate(access, organizationId) {
      authorize(access, Permission.AnalyticsExportSensitive, { requireFreshSession: true })
      await rateLimiter.enforce(RateLimitPolicies.ExportRequest, { organizationId })
    },

    async create(access, organizationId, input, transaction) {
      authorize(access, Permission.AnalyticsExportSensitive, { requireFreshSession: true })
      const actorUserId = access.actor?.userId
      if (actorUserId === undefined) throw forbidden()
      if (transaction === undefined) {
        await rateLimiter.enforce(RateLimitPolicies.ExportRequest, { organizationId })
      }

      const filters = validateFilters(input.exportType, input.filters)

      const execute = async (tx: PrismaTransactionClient) => {
        // The limit row is both policy and mutex. Creating it lazily is safe;
        // locking it serializes concurrent requests before either counts or
        // creates a pending export, so the configured capacity cannot be
        // overrun by a check-then-insert race.
        await tx.$executeRaw`
          insert into organization_limit (organization_id, updated_at)
          values (${organizationId}::uuid, now())
          on conflict (organization_id) do nothing
        `
        await tx.$queryRaw`
          select organization_id from organization_limit
          where organization_id = ${organizationId}::uuid
          for update
        `
        const organizationLimit = await tx.organizationLimit.findUniqueOrThrow({
          where: { organizationId },
          select: { maxConcurrentExports: true },
        })
        const inFlight = await tx.dataExport.count({
          where: { organizationId, status: { in: ['PENDING', 'PROCESSING'] } },
        })
        if (inFlight >= organizationLimit.maxConcurrentExports) {
          throw conflict(
            ErrorCode.CONFLICT,
            'The organization has reached its concurrent export limit.',
          )
        }

        const exportRow = await repository.create(tx, {
          id: newId(),
          organizationId,
          requestedByUserId: actorUserId,
          exportType: input.exportType,
          filters,
        })

        await audit.write(tx, {
          organizationId,
          actorType: 'USER',
          actorUserId,
          action: AuditAction.ExportRequested,
          resourceType: 'data_export',
          resourceId: exportRow.id,
          summary: `Requested a ${input.exportType} export.`,
        })

        await outbox.write(tx, {
          eventType: 'export.requested',
          queueName: QueueName.Exports,
          aggregateType: 'data_export',
          aggregateId: exportRow.id,
          organizationId,
          dedupeKey: `export-requested:${exportRow.id}`,
          payload: { exportId: exportRow.id, organizationId },
        })

        return exportRow
      }

      if (transaction !== undefined) return execute(transaction)
      return transactions.withTenant(organizationId, execute, { actorUserId })
    },

    async list(access, organizationId, query) {
      authorize(access, Permission.AnalyticsExportSensitive)
      const page = toPageRequest(query, limits)
      return transactions.withTenant(organizationId, (tx) =>
        repository.list(tx, organizationId, page),
      )
    },

    async get(access, organizationId, exportId) {
      authorize(access, Permission.AnalyticsExportSensitive)
      const exportRow = await transactions.withTenant(organizationId, (tx) =>
        repository.findById(tx, organizationId, exportId),
      )
      if (exportRow === null) throw notFound('Export not found.')
      return exportRow
    },

    async getDownloadUrl(access, organizationId, exportId) {
      authorize(access, Permission.AnalyticsExportSensitive, { requireFreshSession: true })
      const exportRow = await transactions.withTenant(organizationId, (tx) =>
        repository.findById(tx, organizationId, exportId),
      )
      if (exportRow === null) throw notFound('Export not found.')
      if (exportRow.status !== 'COMPLETED' || exportRow.storageKey === null) {
        throw conflict(ErrorCode.CONFLICT, 'This export is not ready for download yet.')
      }

      const ttlSeconds = config.objectStorage.downloadUrlTtlSeconds
      const downloadUrl = await objectStorage.presignDownloadUrl(exportRow.storageKey, ttlSeconds)
      return { downloadUrl, expiresAt: new Date(Date.now() + ttlSeconds * 1000).toISOString() }
    },

    async remove(access, organizationId, exportId) {
      authorize(access, Permission.AnalyticsExportSensitive, { requireFreshSession: true })
      const actorUserId = access.actor?.userId
      if (actorUserId === undefined) throw forbidden()

      const exportRow = await transactions.withTenant(organizationId, (tx) =>
        repository.findById(tx, organizationId, exportId),
      )
      if (exportRow === null) throw notFound('Export not found.')

      if (exportRow.storageKey !== null) {
        await objectStorage.deleteObject(exportRow.storageKey)
      }

      await transactions.withTenant(
        organizationId,
        async (tx) => {
          await repository.delete(tx, organizationId, exportId)

          await audit.write(tx, {
            organizationId,
            actorType: 'USER',
            actorUserId,
            action: AuditAction.ExportDeleted,
            resourceType: 'data_export',
            resourceId: exportId,
            summary: `Deleted a ${exportRow.exportType} export.`,
          })
        },
        { actorUserId },
      )
    },
  }
}
